-- Migration: Add Unpaid Leave Types for ACP Calculation
-- Date: 2025-11-15
-- Purpose: Add 10 unpaid leave types that are NOT deductible for ACP (is_paid = false)
-- These leave types reduce "jours payés" in ACP calculation

--> statement-breakpoint
-- 1. Permission accordée (Granted Permission)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'permission',
  '{"fr": "Permission accordée", "en": "Granted Permission"}'::jsonb,
  '{"fr": "Autorisation de s''absenter pour raisons personnelles (rendez-vous médicaux, démarches administratives). Non rémunéré et déduit du calcul ACP.", "en": "Short leave for personal reasons (medical appointments, administrative errands). Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'configurable',
  NULL,
  'permission',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  0,
  0.1,
  5.0,
  true,
  false,
  true,
  100
);

--> statement-breakpoint
-- 2. Congé sans solde (Unpaid Leave)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'unpaid_leave',
  '{"fr": "Congé sans solde", "en": "Unpaid Leave"}'::jsonb,
  '{"fr": "Congé non rémunéré pour convenances personnelles. Nécessite l''accord de l''employeur. Déduit du calcul ACP.", "en": "Unpaid leave for personal reasons. Requires employer approval. Deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 26.5',
  'unpaid_leave',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  30,
  1.0,
  365.0,
  true,
  false,
  true,
  101
);

--> statement-breakpoint
-- 3. Absence non justifiée (Unjustified Absence)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'unjustified_absence',
  '{"fr": "Absence non justifiée", "en": "Unjustified Absence"}'::jsonb,
  '{"fr": "Absence sans autorisation préalable ni justificatif valable. Non rémunéré et déduit du calcul ACP. Peut entraîner des sanctions disciplinaires.", "en": "Absence without prior authorization or valid justification. Unpaid and deducted from ACP calculation. May lead to disciplinary action."}'::jsonb,
  'unpaid',
  'locked',
  'Code du Travail Article 17',
  'unjustified_absence',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  false,
  NULL,
  0.1,
  365.0,
  false,
  false,
  true,
  102
);

--> statement-breakpoint
-- 4. Suspension disciplinaire / Mise à pied (Disciplinary Suspension)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'disciplinary_suspension',
  '{"fr": "Mise à pied disciplinaire", "en": "Disciplinary Suspension"}'::jsonb,
  '{"fr": "Suspension temporaire suite à une faute. Non rémunéré et déduit du calcul ACP. Doit respecter la procédure disciplinaire légale.", "en": "Temporary suspension following misconduct. Unpaid and deducted from ACP calculation. Must follow legal disciplinary procedure."}'::jsonb,
  'unpaid',
  'locked',
  'Convention Collective Article 29',
  'disciplinary_suspension',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  NULL,
  1.0,
  8.0,
  false,
  false,
  true,
  103
);

--> statement-breakpoint
-- 5. Congé parental non rémunéré (Unpaid Parental Leave)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'unpaid_parental',
  '{"fr": "Congé parental non rémunéré", "en": "Unpaid Parental Leave"}'::jsonb,
  '{"fr": "Prolongation du congé parental au-delà de la période légale rémunérée. Non rémunéré et déduit du calcul ACP.", "en": "Extension of parental leave beyond paid legal period. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 23.6',
  'unpaid_parental',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  60,
  7.0,
  365.0,
  true,
  false,
  true,
  104
);

--> statement-breakpoint
-- 6. Congé pour convenance personnelle (Personal Convenience Leave)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'personal_convenience',
  '{"fr": "Congé pour convenance personnelle", "en": "Personal Convenience Leave"}'::jsonb,
  '{"fr": "Congé pour événements personnels (déménagement, travaux, cérémonies familiales). Accord de l''employeur requis. Non rémunéré et déduit du calcul ACP.", "en": "Leave for personal events (moving, construction, family ceremonies). Requires employer approval. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'freeform',
  NULL,
  'personal_convenience',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  30,
  1.0,
  90.0,
  true,
  false,
  true,
  105
);

--> statement-breakpoint
-- 7. Congé de formation non rémunéré (Unpaid Training Leave)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'unpaid_training',
  '{"fr": "Congé de formation non rémunéré", "en": "Unpaid Training Leave"}'::jsonb,
  '{"fr": "Congé pour formation personnelle non prise en charge par l''employeur. Non rémunéré et déduit du calcul ACP.", "en": "Leave for personal training not sponsored by employer. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 32.5',
  'unpaid_training',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  60,
  1.0,
  180.0,
  true,
  false,
  true,
  106
);

--> statement-breakpoint
-- 8. Jours de grève (Strike Days)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'strike',
  '{"fr": "Jours de grève", "en": "Strike Days"}'::jsonb,
  '{"fr": "Participation à une grève légale. Droit constitutionnel protégé. Non rémunéré et déduit du calcul ACP.", "en": "Participation in legal strike. Protected constitutional right. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'locked',
  'Code du Travail Article 40',
  'strike',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  false,
  NULL,
  0.5,
  NULL,
  false,
  false,
  true,
  107
);

--> statement-breakpoint
-- 9. Congé sabbatique (Sabbatical Leave)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'sabbatical',
  '{"fr": "Congé sabbatique", "en": "Sabbatical Leave"}'::jsonb,
  '{"fr": "Congé de longue durée pour projets personnels. Généralement accordé après plusieurs années de service. Non rémunéré et déduit du calcul ACP.", "en": "Long-term leave for personal projects. Generally granted after several years of service. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'freeform',
  NULL,
  'sabbatical',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  90,
  30.0,
  365.0,
  true,
  false,
  true,
  108
);

--> statement-breakpoint
-- 10. Autorisation d'absence exceptionnelle non payée (Exceptional Unpaid Absence)
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order"
) VALUES (
  'CI',
  'exceptional_unpaid',
  '{"fr": "Absence exceptionnelle non payée", "en": "Exceptional Unpaid Absence"}'::jsonb,
  '{"fr": "Autorisation d''absence pour événements familiaux ou communautaires non couverts par les congés légaux payés. Non rémunéré et déduit du calcul ACP.", "en": "Leave authorization for family or community events not covered by paid legal leave. Unpaid and deducted from ACP calculation."}'::jsonb,
  'unpaid',
  'configurable',
  NULL,
  'exceptional_unpaid',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  7,
  1.0,
  10.0,
  true,
  false,
  true,
  109
);
