-- Migration: Add Permissions Exceptionnelles (Article 25.12 Code du Travail CI)
-- Date: 2025-12-09
-- Purpose: Add paid permission types for family events as required by Ivory Coast labor law
-- These are PAID permissions, separate from annual leave, max 10 days/year total combined
-- Employee must have 6+ months tenure to be eligible

--> statement-breakpoint
-- 0. Add metadata column to time_off_policies (to store permission-specific rules)
-- This allows us to track permission_category, min_tenure_months, etc. per policy
ALTER TABLE "time_off_policies" ADD COLUMN IF NOT EXISTS "metadata" jsonb;

--> statement-breakpoint
-- 1. Fix Birth leave: 3 days -> 2 days (legal requirement per Article 25.12)
UPDATE "time_off_policy_templates"
SET
  "default_accrual_rate" = 2.00,
  "description" = '{"fr": "2 jours payés lors de la naissance d''un enfant (Article 25.12)", "en": "2 paid days for child birth (Article 25.12)"}'::jsonb,
  "legal_reference" = 'Code du Travail Article 25.12',
  "metadata" = '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
WHERE "country_code" = 'CI' AND "code" = 'SPECIAL_BIRTH_CI';

--> statement-breakpoint
-- 2. Update existing Marriage leave to have proper metadata
UPDATE "time_off_policy_templates"
SET
  "legal_reference" = 'Code du Travail Article 25.12',
  "metadata" = '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
WHERE "country_code" = 'CI' AND "code" = 'SPECIAL_MARRIAGE_CI';

--> statement-breakpoint
-- 3. Marriage of child (2 days) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_MARRIAGE_CHILD_CI',
  '{"fr": "Mariage d''un enfant", "en": "Child''s Marriage"}'::jsonb,
  '{"fr": "2 jours payés pour le mariage d''un enfant (Article 25.12). Ancienneté minimum: 6 mois.", "en": "2 paid days for child''s marriage (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_marriage_child',
  'fixed',
  2.00,
  2.00,
  NULL,
  true,
  1.0,
  true,
  7,
  1.0,
  2.0,
  false,
  false,
  true,
  31,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 4. Marriage of sibling (2 days) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_MARRIAGE_SIBLING_CI',
  '{"fr": "Mariage d''un frère ou d''une soeur", "en": "Sibling''s Marriage"}'::jsonb,
  '{"fr": "2 jours payés pour le mariage d''un frère ou d''une soeur (Article 25.12). Ancienneté minimum: 6 mois.", "en": "2 paid days for sibling''s marriage (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_marriage_sibling',
  'fixed',
  2.00,
  2.00,
  NULL,
  true,
  1.0,
  true,
  7,
  1.0,
  2.0,
  false,
  false,
  true,
  32,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 5. Death of parent - father or mother (5 days) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_DEATH_PARENT_CI',
  '{"fr": "Décès du père ou de la mère", "en": "Death of Parent"}'::jsonb,
  '{"fr": "5 jours payés pour le décès du père ou de la mère (Article 25.12). Ancienneté minimum: 6 mois.", "en": "5 paid days for death of father or mother (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_death_parent',
  'fixed',
  5.00,
  5.00,
  NULL,
  true,
  1.0,
  true,
  0,
  1.0,
  5.0,
  false,
  false,
  true,
  33,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 6. Death of sibling (2 days) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_DEATH_SIBLING_CI',
  '{"fr": "Décès d''un frère ou d''une soeur", "en": "Death of Sibling"}'::jsonb,
  '{"fr": "2 jours payés pour le décès d''un frère ou d''une soeur (Article 25.12). Ancienneté minimum: 6 mois.", "en": "2 paid days for death of sibling (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_death_sibling',
  'fixed',
  2.00,
  2.00,
  NULL,
  true,
  1.0,
  true,
  0,
  1.0,
  2.0,
  false,
  false,
  true,
  34,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 7. Death of in-laws - father-in-law or mother-in-law (2 days) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_DEATH_INLAW_CI',
  '{"fr": "Décès d''un beau-père ou d''une belle-mère", "en": "Death of In-Law"}'::jsonb,
  '{"fr": "2 jours payés pour le décès d''un beau-père ou d''une belle-mère (Article 25.12). Ancienneté minimum: 6 mois.", "en": "2 paid days for death of father-in-law or mother-in-law (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_death_inlaw',
  'fixed',
  2.00,
  2.00,
  NULL,
  true,
  1.0,
  true,
  0,
  1.0,
  2.0,
  false,
  false,
  true,
  35,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 8. Child baptism (1 day) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_BAPTISM_CI',
  '{"fr": "Baptême d''un enfant", "en": "Child''s Baptism"}'::jsonb,
  '{"fr": "1 jour payé pour le baptême d''un enfant (Article 25.12). Ancienneté minimum: 6 mois.", "en": "1 paid day for child''s baptism (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_baptism',
  'fixed',
  1.00,
  1.00,
  NULL,
  true,
  1.0,
  true,
  7,
  1.0,
  1.0,
  false,
  false,
  true,
  36,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 9. First communion (1 day) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_COMMUNION_CI',
  '{"fr": "Première communion d''un enfant", "en": "Child''s First Communion"}'::jsonb,
  '{"fr": "1 jour payé pour la première communion d''un enfant (Article 25.12). Ancienneté minimum: 6 mois.", "en": "1 paid day for child''s first communion (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_communion',
  'fixed',
  1.00,
  1.00,
  NULL,
  true,
  1.0,
  true,
  7,
  1.0,
  1.0,
  false,
  false,
  true,
  37,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 10. Moving house / Demenagement (1 day) - PAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_DEMENAGEMENT_CI',
  '{"fr": "Déménagement", "en": "Moving House"}'::jsonb,
  '{"fr": "1 jour payé pour un déménagement (Article 25.12). Ancienneté minimum: 6 mois.", "en": "1 paid day for moving house (Article 25.12). Minimum tenure: 6 months."}'::jsonb,
  'special',
  'locked',
  'Code du Travail Article 25.12',
  'permission_demenagement',
  'fixed',
  1.00,
  1.00,
  NULL,
  true,
  1.0,
  true,
  7,
  1.0,
  1.0,
  false,
  false,
  true,
  38,
  '{"permission_category": "famille_legale", "min_tenure_months": 6}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- ============================================================
-- UNPAID PERMISSIONS (Autres membres de la famille + Délai de route)
-- ============================================================

-- 11. Travel days - near (<400km) - 2 days UNPAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_TRAVEL_NEAR_CI',
  '{"fr": "Délai de route (<400km)", "en": "Travel Days (Near)"}'::jsonb,
  '{"fr": "2 jours non payés de délai de route si l''événement familial est à moins de 400km (Article 25.12).", "en": "2 unpaid travel days if family event is less than 400km away (Article 25.12)."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 25.12',
  'permission_travel_near',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  0,
  1.0,
  2.0,
  true,
  false,
  true,
  39,
  '{"travel_type": "near", "max_distance_km": 400}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 12. Travel days - far (>400km) - 3 days UNPAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_TRAVEL_FAR_CI',
  '{"fr": "Délai de route (>400km)", "en": "Travel Days (Far)"}'::jsonb,
  '{"fr": "3 jours non payés de délai de route si l''événement familial est à plus de 400km (Article 25.12).", "en": "3 unpaid travel days if family event is more than 400km away (Article 25.12)."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 25.12',
  'permission_travel_far',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  0,
  1.0,
  3.0,
  true,
  false,
  true,
  40,
  '{"travel_type": "far", "min_distance_km": 400}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 13. Death of other family members (2 days) - UNPAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_OTHER_FAMILY_DEATH_CI',
  '{"fr": "Décès - autres membres de la famille", "en": "Death - Other Family Members"}'::jsonb,
  '{"fr": "2 jours non payés pour le décès d''autres membres de la famille non couverts par les permissions légales (Article 25.12).", "en": "2 unpaid days for death of other family members not covered by legal permissions (Article 25.12)."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 25.12',
  'permission_other_death',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  0,
  1.0,
  2.0,
  true,
  false,
  true,
  41,
  '{"permission_category": "autres_famille"}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;

--> statement-breakpoint
-- 14. Marriage of other family members (1 day) - UNPAID
INSERT INTO "time_off_policy_templates" (
  "country_code",
  "code",
  "name",
  "description",
  "category",
  "compliance_level",
  "legal_reference",
  "policy_type",
  "accrual_method",
  "default_accrual_rate",
  "default_max_balance",
  "carryover_months",
  "is_paid",
  "payment_rate",
  "requires_approval",
  "advance_notice_days",
  "min_days_per_request",
  "max_days_per_request",
  "can_deactivate",
  "can_modify_accrual",
  "is_active",
  "display_order",
  "metadata"
) VALUES (
  'CI',
  'PERMISSION_OTHER_FAMILY_MARRIAGE_CI',
  '{"fr": "Mariage - autres membres de la famille", "en": "Marriage - Other Family Members"}'::jsonb,
  '{"fr": "1 jour non payé pour le mariage d''autres membres de la famille non couverts par les permissions légales (Article 25.12).", "en": "1 unpaid day for marriage of other family members not covered by legal permissions (Article 25.12)."}'::jsonb,
  'unpaid',
  'configurable',
  'Code du Travail Article 25.12',
  'permission_other_marriage',
  'none',
  0.00,
  NULL,
  NULL,
  false,
  0.0,
  true,
  7,
  1.0,
  1.0,
  true,
  false,
  true,
  42,
  '{"permission_category": "autres_famille"}'::jsonb
) ON CONFLICT ("country_code", "code") DO NOTHING;
